// Generated by scripts/generate-workspace-routes.mjs. Do not edit directly.
export { default } from "@/app/(marketing)/compare/[competitor]/page";
export * from "@/app/(marketing)/compare/[competitor]/page";
