import {
  CalendarCheck2,
  CalendarClock,
  CircleDollarSign,
  Eye,
  FileText,
  Mail,
  MessageSquare,
  Pencil,
  Plus,
  Receipt,
  RefreshCcw,
  Rocket,
  Send,
  Sparkles,
  Trash2,
  UserPlus,
  UserMinus,
  UserCheck,
  Paperclip,
  CheckCircle2,
  XCircle,
  LogIn,
  ListChecks,
  Zap,
  ZapOff,
  Wallet,
  FileSignature,
  RotateCcw,
  Ban,
  Repeat,
  AlertTriangle,
  Play,
  Square,
  Timer,
  Gauge,
  type LucideIcon,
} from "lucide-react";

import type { BadgeProps } from "@/components/ui/badge";

/**
 * Single source of truth for activity-type badge variants and icons, shared
 * by the dashboard feed, client/project activity trails, and the Unified
 * Client Timeline. Unknown types fall back to "secondary" / Sparkles at the
 * call site.
 */
export const ACTIVITY_VARIANT: Record<string, BadgeProps["variant"]> = {
  "Client Created": "success",
  "Client Updated": "info",
  "Note Added": "secondary",
  "Client Archived": "warning",
  "Client Restored": "success",
  "Project Created": "success",
  "Project Updated": "info",
  "Project Started": "info",
  "Project Completed": "success",
  "Project Cancelled": "destructive",
  "Status Changed": "info",
  "Project Archived": "warning",
  "Invoice Created": "success",
  "Invoice Updated": "info",
  "Invoice Sent": "info",
  "Invoice Viewed": "secondary",
  "Invoice Paid": "success",
  "Invoice Unpaid": "warning",
  "Invoice Archived": "warning",
  "Payment Received": "success",
  "File Uploaded": "secondary",
  "Contract Uploaded": "secondary",
  "Team Member Invited": "info",
  "Team Member Joined": "success",
  "Team Member Removed": "destructive",
  "Invite Cancelled": "warning",
  "Meeting Scheduled": "info",
  "Meeting Completed": "success",
  "Email Sent": "secondary",
  "Portal Comment": "secondary",
  "Portal Viewed": "secondary",
  "Login Activity": "secondary",
  "Custom Event": "outline",
  "Task Completed": "success",
  "Automation Succeeded": "success",
  "Automation Failed": "destructive",
  "Cost Logged": "secondary",
  "Proposal Created": "secondary",
  "Proposal Sent": "info",
  "Proposal Viewed": "secondary",
  "Proposal Accepted": "success",
  "Proposal Rejected": "destructive",
  "Proposal Expired": "warning",
  "Proposal Cancelled": "warning",
  "Subscription Created": "success",
  "Subscription Renewed": "success",
  "Subscription Failed": "destructive",
  "Timer Started": "info",
  "Timer Stopped": "secondary",
  "Hours Logged": "secondary",
  "Workload Changed": "warning",
};

/** Icon shown in the timeline bubble for each activity type. */
export const ACTIVITY_ICON: Record<string, LucideIcon> = {
  "Client Created": Plus,
  "Client Updated": Pencil,
  "Note Added": MessageSquare,
  "Client Archived": Trash2,
  "Client Restored": RefreshCcw,
  "Project Created": Plus,
  "Project Updated": Pencil,
  "Project Started": Rocket,
  "Project Completed": CheckCircle2,
  "Project Cancelled": XCircle,
  "Status Changed": RefreshCcw,
  "Project Archived": Trash2,
  "Invoice Created": FileText,
  "Invoice Updated": Pencil,
  "Invoice Sent": Send,
  "Invoice Viewed": Eye,
  "Invoice Paid": CircleDollarSign,
  "Invoice Unpaid": Receipt,
  "Invoice Archived": Trash2,
  "Payment Received": CircleDollarSign,
  "File Uploaded": Paperclip,
  "Contract Uploaded": FileText,
  "Team Member Invited": UserPlus,
  "Team Member Joined": UserCheck,
  "Team Member Removed": UserMinus,
  "Invite Cancelled": UserMinus,
  "Meeting Scheduled": CalendarClock,
  "Meeting Completed": CalendarCheck2,
  "Email Sent": Mail,
  "Portal Comment": MessageSquare,
  "Portal Viewed": Eye,
  "Login Activity": LogIn,
  "Custom Event": Sparkles,
  "Task Completed": ListChecks,
  "Automation Succeeded": Zap,
  "Automation Failed": ZapOff,
  "Cost Logged": Wallet,
  "Proposal Created": FileSignature,
  "Proposal Sent": Send,
  "Proposal Viewed": Eye,
  "Proposal Accepted": CheckCircle2,
  "Proposal Rejected": XCircle,
  "Proposal Expired": AlertTriangle,
  "Proposal Cancelled": Ban,
  "Subscription Created": Repeat,
  "Subscription Renewed": RotateCcw,
  "Subscription Failed": AlertTriangle,
  "Timer Started": Play,
  "Timer Stopped": Square,
  "Hours Logged": Timer,
  "Workload Changed": Gauge,
};

export const DEFAULT_ACTIVITY_ICON: LucideIcon = Sparkles;
