// Generated by scripts/generate-workspace-routes.mjs. Do not edit directly.
export { default } from "@/app/(marketing)/features/team-collaboration/page";
export * from "@/app/(marketing)/features/team-collaboration/page";
