// Generated by scripts/generate-workspace-routes.mjs. Do not edit directly.
export { default } from "@/app/(marketing)/resources/[category]/[slug]/page";
export * from "@/app/(marketing)/resources/[category]/[slug]/page";
