// Generated by scripts/generate-workspace-routes.mjs. Do not edit directly.
export { default } from "@/app/(marketing)/blog/author/[author]/page";
export * from "@/app/(marketing)/blog/author/[author]/page";
