// Generated by scripts/generate-workspace-routes.mjs. Do not edit directly.
export { default } from "@/app/(app)/invoices/[invoiceId]/edit/page";
export * from "@/app/(app)/invoices/[invoiceId]/edit/page";
