// Generated by scripts/generate-workspace-routes.mjs. Do not edit directly.
export { default } from "@/app/(marketing)/solutions/[industry]/page";
export * from "@/app/(marketing)/solutions/[industry]/page";
